export const FILTER_NAME_MAKE = 'make'
export const FILTER_NAME_MODEL = 'model'
export const FILTER_NAME_BODY_TYPE = 'bodyType'
export const FILTER_NAME_TRANSMISSION = 'transmission'
export const FILTER_NAME_PRICE = 'price'
export const FILTER_NAME_YEAR = 'year'
export const FILTER_NAME_KILOMETRES = 'kilometres'
